### ISSUE TITLE
release版windows X64无法运行，缺少库

### ISSUE THREAD

**Issue by yachli** [caozhanhao/wxserver#1]
缺少libwinpthread-1.dll等几个库，从别处下载的放到同目录下也运行不起来，报0xc000007b错误

**Comment by yachli** [comment]
老师能上传完整的文件吗？很好玩的样子

**Comment by caozhanhao** [comment]
https://github.com/caozhanhao/wxserver/releases/tag/v0.3.3
这次我把运行库和配置文件也打包进去了，再试试吧😀

**Comment by yachli** [comment]
还差一个libstdc++-6.dll，在网上下载了几个版本的，都不适用，报无法定位程序输入点

**Comment by yachli** [comment]
win11 X64

**Comment by safir98** [comment]
缺少运行文件的问题解决了吗

**Comment by caozhanhao** [comment]
https://github.com/caozhanhao/wxserver/releases/tag/v0.3.3
抱歉，前两天上学没有时间处理，这次应该可以了。😃
