### ISSUE TITLE
你好，可否编译一份Hugging Face版本

### ISSUE THREAD

**Issue by safir98** [caozhanhao/wxserver#2]
阅读开发者文档发现使用Hugging Face版本需要重新编译，请问作者可否编译一份上传

**Comment by caozhanhao** [comment]
好的，我把两个整合成一个了。
https://github.com/caozhanhao/wxserver/releases/tag/v0.3.4
用记事本打开config.czh，把["bot"]["bot"]改为`hugging_face`, 填写["hugging_face"]的model和token即可

如下
```
bot:
    bot = "hugging_face";
    proxy = null;
    proxy_port = null;
end;

hugging_face:
    model = "ingen51/DialoGPT-medium-GPT4";
    token = "input your Hugging Face token.";
end;
```

**Comment by safir98** [comment]
> 好的，我把两个整合成一个了。 https://github.com/caozhanhao/wxserver/releases/tag/v0.3.4 用记事本打开config.czh，把["bot"]["bot"]改为, 填写["hugging_face"]的model和token即可`hugging_face`
> 
> 如下
> 
> ```
> bot:
>     bot = "hugging_face";
>     proxy = null;
>     proxy_port = null;
> end;
> 
> hugging_face:
>     model = "ingen51/DialoGPT-medium-GPT4";
>     token = "input your Hugging Face token.";
> end;
> ```

谢谢作者大佬编译打包    :)
